name: rtbfa
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.13.1
  - pip
  - pip:
    - gym
    - numpy
    - matplotlib
    - torch>=1.10,<3.0
    - tqdm
    - stable-baselines3
    - shimmy>=2.0
